### ISSUE TITLE
Personal Account Page Error

### ISSUE THREAD

**Issue by SturmR** [bounswe/bounswe2024group10#494]
When clicking the account page icon on the sidebar or clicking the username on the right menu, basically trying to access the account page, we get this error:

Uncaught runtime errors:
×
ERROR
post.content.find is not a function
TypeError: post.content.find is not a function
    at Post (http://localhost:3000/static/js/bundle.js:914:56)
    at renderWithHooks (http://localhost:3000/static/js/bundle.js:32676:22)
    at mountIndeterminateComponent (http://localhost:3000/static/js/bundle.js:36647:17)
    at beginWork (http://localhost:3000/static/js/bundle.js:37950:20)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:22932:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:22976:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:23033:35)
    at beginWork$1 (http://localhost:3000/static/js/bundle.js:42931:11)
    at performUnitOfWork (http://localhost:3000/static/js/bundle.js:42179:16)
    at workLoopSync (http://localhost:3000/static/js/bundle.js:42102:9)
    
 We should see the account page instead.

**Comment by SturmR** [comment]
Issue appears to have stemmed from post.content having changed its type. I Restructured the mock posts in the account page to fit the current structure of a post.
